In [30]:
# Importing all libraries :

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

In [3]:
df = pd.read_csv('cars_class.csv')
df.head()

ID  Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
0   1    88    39      70     166          66         7      148     44   
1   2    85    35      64     129          57         6      116     57   
2   3    91    41      84     141          57         9      149     45   
3   4   102    54      98     177          56        10      219     31   
4   5    87    39      74     152          58         6      151     44   

   Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
0            19         134           167           332     143          69   
1            17         125           138           200     123          65   
2            19         143           170           330     158          72   
3            25         171           219           706     223          72   
4            19         136           174           337     140          70   

   Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  Class  
0           5          13         193      201      0  
1           1          23         196      203      3  
2           9          14         189      199      3  
3           5          17         186      196      1  
4           1          33         187      196      2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 719 entries, 0 to 718
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            719 non-null    int64
 1   Comp          719 non-null    int64
 2   Circ          719 non-null    int64
 3   D.Circ        719 non-null    int64
 4   Rad.Ra        719 non-null    int64
 5   Pr.Axis.Ra    719 non-null    int64
 6   Max.L.Ra      719 non-null    int64
 7   Scat.Ra       719 non-null    int64
 8   Elong         719 non-null    int64
 9   Pr.Axis.Rect  719 non-null    int64
 10  Max.L.Rect    719 non-null    int64
 11  Sc.Var.Maxis  719 non-null    int64
 12  Sc.Var.maxis  719 non-null    int64
 13  Ra.Gyr        719 non-null    int64
 14  Skew.Maxis    719 non-null    int64
 15  Skew.maxis    719 non-null    int64
 16  Kurt.maxis    719 non-null    int64
 17  Kurt.Maxis    719 non-null    int64
 18  Holl.Ra       719 non-null    int64
 19  Class         719 non-null   

In [5]:
df.describe()

ID        Comp        Circ      D.Circ      Rad.Ra  Pr.Axis.Ra  \
count  719.000000  719.000000  719.000000  719.000000  719.000000  719.000000   
mean   360.000000   93.435327   44.851182   81.723227  168.579972   61.847010   
std    207.701709    8.111406    6.150286   15.528208   33.809172    8.259136   
min      1.000000   73.000000   33.000000   40.000000  105.000000   47.000000   
25%    180.500000   87.000000   40.000000   70.000000  141.000000   57.000000   
50%    360.000000   93.000000   44.000000   79.000000  166.000000   61.000000   
75%    539.500000   99.000000   49.000000   96.000000  194.500000   65.000000   
max    719.000000  119.000000   59.000000  110.000000  333.000000  138.000000   

         Max.L.Ra     Scat.Ra       Elong  Pr.Axis.Rect  Max.L.Rect  \
count  719.000000  719.000000  719.000000    719.000000  719.000000   
mean     8.625869  168.137691   41.075104     20.531293  148.030598   
std      4.916908   32.937591    7.764459      2.560969   14.560092   
min      2.000000  112.000000   26.000000     17.000000  118.000000   
25%      6.000000  146.000000   33.000000     19.000000  137.000000   
50%      8.000000  157.000000   43.000000     20.000000  146.000000   
75%     10.000000  197.500000   46.000000     23.000000  159.000000   
max     55.000000  265.000000   61.000000     29.000000  188.000000   

       Sc.Var.Maxis  Sc.Var.maxis      Ra.Gyr  Skew.Maxis  Skew.maxis  \
count    719.000000    719.000000  719.000000  719.000000  719.000000   
mean     188.168289    436.215577  174.726008   72.682893    6.343533   
std       31.235395    174.964977   32.149568    7.542055    4.856169   
min      130.000000    184.000000  109.000000   59.000000    0.000000   
25%      167.000000    317.000000  149.000000   68.000000    2.000000   
50%      178.000000    362.000000  174.000000   72.000000    6.000000   
75%      216.000000    584.500000  198.000000   76.000000    9.000000   
max      320.000000   1018.000000  262.000000  135.000000   22.000000   

       Kurt.maxis  Kurt.Maxis     Holl.Ra       Class  
count  719.000000  719.000000  719.000000  719.000000  
mean    12.394993  188.798331  195.407510    1.470097  
std      8.742511    6.048522    7.235166    1.126477  
min      0.000000  176.000000  181.000000    0.000000  
25%      5.500000  184.000000  190.000000    0.000000  
50%     11.000000  188.000000  196.000000    1.000000  
75%     18.000000  193.000000  201.000000    2.000000  
max     41.000000  204.000000  211.000000    3.000000

In [6]:
df.shape

(719, 20)

DATA PREPROESSING

In [7]:
#checking any duplicates
df.duplicated(subset = ['ID']).sum()

0

In [8]:
df = df.drop(['ID'], axis =1) # Index column is an insignificant column.

In [9]:
df.isnull().sum()

Comp            0
Circ            0
D.Circ          0
Rad.Ra          0
Pr.Axis.Ra      0
Max.L.Ra        0
Scat.Ra         0
Elong           0
Pr.Axis.Rect    0
Max.L.Rect      0
Sc.Var.Maxis    0
Sc.Var.maxis    0
Ra.Gyr          0
Skew.Maxis      0
Skew.maxis      0
Kurt.maxis      0
Kurt.Maxis      0
Holl.Ra         0
Class           0
dtype: int64

DATA VISUALIZATION

In [12]:
cars_numeric = df.select_dtypes(include =['int64'])
cars_numeric

Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
0      88    39      70     166          66         7      148     44   
1      85    35      64     129          57         6      116     57   
2      91    41      84     141          57         9      149     45   
3     102    54      98     177          56        10      219     31   
4      87    39      74     152          58         6      151     44   
..    ...   ...     ...     ...         ...       ...      ...    ...   
714   111    58     105     183          51         6      265     26   
715    93    43      76     149          57         7      149     44   
716    90    42      63     144          59         7      131     50   
717   101    56     101     231          72        10      217     31   
718    99    38      74     184          66         6      164     39   

     Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
0              19         134           167           332     143          69   
1              17         125           138           200     123          65   
2              19         143           170           330     158          72   
3              25         171           219           706     223          72   
4              19         136           174           337     140          70   
..            ...         ...           ...           ...     ...         ...   
714            29         174           285          1018     255          85   
715            19         143           172           335     176          69   
716            18         142           154           259     162          65   
717            24         171           232           698     216          72   
718            20         131           193           414     137          71   

     Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  Class  
0             5          13         193      201      0  
1             1          23         196      203      3  
2             9          14         189      199      3  
3             5          17         186      196      1  
4             1          33         187      196      2  
..          ...         ...         ...      ...    ...  
714           4           8         181      183      0  
715          14           0         189      194      2  
716          15           3         197      204      3  
717           2           6         187      197      2  
718           2          22         200      202      0  

[719 rows x 19 columns]

In [14]:
# plt.figure(figsize = (20,20))
# sns.heatmap(df.corr(), annot = True ,cmap = 'YlGnBu')
# plt.show()

In [15]:
df_train, df_test = train_test_split(df, train_size = 0.8, test_size = 0.2, random_state = 100)

In [16]:
df_train

Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
44    100    57     107     207          63        11      227     30   
402    95    44      84     158          62        10      145     46   
474    90    38      79     185          69         6      160     40   
31     88    34      69     152          57         5      138     48   
272   109    52     104     199          60        12      215     31   
..    ...   ...     ...     ...         ...       ...      ...    ...   
578    96    44      85     166          66        10      155     43   
53    109    47      96     206          64         9      198     33   
350   106    49     106     211          64         9      208     32   
79     93    45      86     201          69         7      184     35   
520    93    42      64     158          68         9      134     49   

     Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
44             25         180           234           756     205          72   
402            19         148           163           312     166          64   
474            20         130           178           393     133          66   
31             18         122           158           284     120          62   
272            24         162           220           691     212          67   
..            ...         ...           ...           ...     ...         ...   
578            19         150           167           355     159          67   
53             23         150           219           586     191          70   
350            24         158           224           645     184          68   
79             22         145           203           523     183          72   
520            18         142           163           268     170          71   

     Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  Class  
44            6          19         186      198      1  
402          10           6         199      206      3  
474           2          14         198      205      0  
31            9          29         204      210      1  
272          11           7         189      199      2  
..          ...         ...         ...      ...    ...  
578           3          10         192      202      3  
53            4          13         190      198      2  
350           1          24         190      202      2  
79            0           4         194      197      0  
520           7          13         192      201      3  

[575 rows x 19 columns]

In [17]:
df_test

Comp  Circ  D.Circ  Rad.Ra  Pr.Axis.Ra  Max.L.Ra  Scat.Ra  Elong  \
198    93    41      75     124          51         7      140     49   
487    81    44      68     120          53         6      151     45   
365   102    54      98     167          53        10      217     31   
622    83    40      53     114          53         6      132     53   
635    85    42      66     122          54         6      148     46   
..    ...   ...     ...     ...         ...       ...      ...    ...   
3     102    54      98     177          56        10      219     31   
666    98    42      90     192          61         9      178     37   
328    94    45      72     179          69         6      156     41   
456   109    49     109     193          59        10      207     32   
171   110    56     103     223          64         5      250     26   

     Pr.Axis.Rect  Max.L.Rect  Sc.Var.Maxis  Sc.Var.maxis  Ra.Gyr  Skew.Maxis  \
198            18         141           164           284     149          77   
487            19         147           170           333     178          86   
365            24         174           228           692     223          72   
622            18         140           142           247     157          86   
635            19         141           172           317     174          88   
..            ...         ...           ...           ...     ...         ...   
3              25         171           219           706     223          72   
666            21         144           189           480     138          61   
328            19         144           181           373     191          69   
456            24         156           225           635     213          70   
171            27         169           280           928     239          85   

     Skew.maxis  Kurt.maxis  Kurt.Maxis  Holl.Ra  Class  
198           5          15         184      185      3  
487           4           5         179      183      0  
365           0          31         187      198      1  
622           8           7         176      183      3  
635           6          14         180      182      0  
..          ...         ...         ...      ...    ...  
3             5          17         186      196      1  
666           3           8         199      208      2  
328           5           5         193      198      0  
456          13          31         191      202      2  
171           4           6         184      183      0  

[144 rows x 19 columns]

In [20]:
y_train = df_train.pop('Class')
X_train = df_train

In [21]:
y_test = df_test.pop('Class')
X_test = df_test

DECISION TREE CLASSIFIER

In [22]:
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

In [28]:
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)
cm

array([[45,  0,  0,  2],
       [11, 20,  0,  0],
       [10, 25,  0,  0],
       [15,  0,  0, 16]], dtype=int64)

In [29]:
dtree_accuracy = accuracy_score(y_test,dtree_predictions)
dtree_accuracy

0.5625

In [40]:
dtree_f1 = f1_score(y_test,dtree_predictions,average='micro')
dtree_f1

0.5625

SVM (SUPPORT VECTOR MACHINE) CLASSIFIER

In [45]:
from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)

In [47]:
# model accuracy for X_test  
accuracy_svm = svm_model_linear.score(X_test, y_test)
accuracy_svm

0.8402777777777778

In [48]:
# creating a confusion matrix
cm_svm = confusion_matrix(y_test, svm_predictions)
cm_svm

array([[45,  0,  0,  2],
       [ 1, 22,  8,  0],
       [ 1,  8, 26,  0],
       [ 1,  1,  1, 28]], dtype=int64)

In [49]:
svm_f1 = f1_score(y_test,svm_predictions,average='micro')
svm_f1

0.8402777777777778

KNN (K-NEAREST NEIGHBORS CLASSIFIER)

In [52]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train)
knn_predictions = knn.predict(X_test)

In [53]:
knn_accuracy = knn.score(X_test, y_test)
knn_accuracy

0.6527777777777778

In [54]:
knn_cm = confusion_matrix(y_test, knn_predictions)
knn_cm

array([[34,  7,  6,  0],
       [ 4, 14, 10,  3],
       [ 3, 16, 15,  1],
       [ 0,  0,  0, 31]], dtype=int64)

In [55]:
knn_f1 = f1_score(y_test,knn_predictions,average='micro')
knn_f1

0.6527777777777778

NAIVE-BAYES CLASSFIER

In [56]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)
gnb_predictions = gnb.predict(X_test)

In [57]:
# accuracy on X_test
gnb_accuracy = gnb.score(X_test, y_test)
gnb_accuracy

0.4375

In [59]:
# creating a confusion matrix
gnb_cm = confusion_matrix(y_test, gnb_predictions)
gnb_cm

array([[ 9, 10,  1, 27],
       [ 0, 16,  4, 11],
       [ 0, 19,  9,  7],
       [ 0,  0,  2, 29]], dtype=int64)

In [60]:
gnb_f1 = f1_score(y_test,gnb_predictions,average='micro')
gnb_f1

0.4375

In [ ]:
# SVM HAS THE HIGHEST ACCURACY WHEN COMPARED WITH DECISION TREE, KNN, NAIVE-BAYES CLASSIFIERS